language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
before_script:
  - npm prune
after_success:
  - npm run test:cov
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
